#!/bin/bash

while getopts "d:" opt; do
  case $opt in
    d)
      domain=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [[ -z $domain ]]
then
  echo "Usage: oif -d domain.com"
  exit 1
fi


echo -e "\033[96mDomain Info:\033[0m"
echo $domain | httpx -duc -silent -sc -cl -title

echo -e "\n\033[96mOrigin IPs Info:\033[0m"
dig=$(dig @1.1.1.1 $domain A +short)
shodan=$(shodan search ssl:$domain --fields ip_str,port --separator ":" | sed 's/:$//' | sed 's/:\(80\|443\)$//')

echo $shodan $dig | tr ' ' '\n' | sort -u | httpx -duc -silent -sc -cl -title

echo -e "\n\033[91mNOTE: Check Same Content Length and Same Title that's Your Origin IPs:\033[0m"
